// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Caml_array = require("rescript/lib/js/caml_array.js");

function make_ports(cnt) {
  var arr = Belt_Array.makeBy(cnt, (function (i) {
          return Belt_Array.makeBy(cnt - i | 0, (function (param) {
                        return new MessageChannel();
                      }));
        }));
  return Belt_Array.makeBy(cnt, (function (i) {
                return Belt_Array.makeBy(cnt, (function (j) {
                              if (i >= j) {
                                return Caml_array.get(Caml_array.get(arr, i), j).port1;
                              } else {
                                return Caml_array.get(Caml_array.get(arr, j), i).port2;
                              }
                            }));
              }));
}

function initWorkers(workers) {
  var cnt = workers.length;
  var ports_array = make_ports(cnt);
  workers.map(function (worker, i) {
        var ports = Caml_array.get(ports_array, i);
        worker.postMessage(ports, ports.map(function (prim) {
                  return prim;
                }));
        
      });
  
}

var MainSide = {
  make_ports: make_ports,
  initWorkers: initWorkers
};

exports.MainSide = MainSide;
/* No side effect */
