// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("rescript/lib/js/caml_option.js");

function lens_a_get(a, param, param$1) {
  return a;
}

function lens_a_put(param, a) {
  return [
          a,
          param[1],
          param[2]
        ];
}

var lens_a = {
  get: lens_a_get,
  put: lens_a_put
};

function lens_b_get(param, b, param$1) {
  return b;
}

function lens_b_put(param, b) {
  return [
          param[0],
          b,
          param[2]
        ];
}

var lens_b = {
  get: lens_b_get,
  put: lens_b_put
};

function lens_c_get(param, param$1, c) {
  return c;
}

function lens_c_put(param, c) {
  return [
          param[0],
          param[1],
          c
        ];
}

var lens_c = {
  get: lens_c_get,
  put: lens_c_put
};

var a_role_meth = {
  call_obj: (function (obj) {
      return obj.a;
    }),
  make_obj: (function (v) {
      return {
              a: v
            };
    })
};

var a = {
  role_meth: a_role_meth,
  role_lens: lens_a
};

var b_role_meth = {
  call_obj: (function (obj) {
      return obj.b;
    }),
  make_obj: (function (v) {
      return {
              b: v
            };
    })
};

var b = {
  role_meth: b_role_meth,
  role_lens: lens_b
};

var c_role_meth = {
  call_obj: (function (obj) {
      return obj.c;
    }),
  make_obj: (function (v) {
      return {
              c: v
            };
    })
};

var c = {
  role_meth: c_role_meth,
  role_lens: lens_c
};

var add_meth = {
  call_obj: (function (obj) {
      return obj.add;
    }),
  make_obj: (function (v) {
      return {
              add: v
            };
    })
};

var add_var = {
  match_var: (function ($$var) {
      if (typeof $$var === "object" && $$var.NAME === "add") {
        return Caml_option.some($$var.VAL);
      }
      
    }),
  make_var: (function (v) {
      return {
              NAME: "add",
              VAL: v
            };
    })
};

var add = {
  meth: add_meth,
  var: add_var
};

var res_meth = {
  call_obj: (function (obj) {
      return obj.res;
    }),
  make_obj: (function (v) {
      return {
              res: v
            };
    })
};

var res_var = {
  match_var: (function ($$var) {
      if (typeof $$var === "object" && $$var.NAME === "res") {
        return Caml_option.some($$var.VAL);
      }
      
    }),
  make_var: (function (v) {
      return {
              NAME: "res",
              VAL: v
            };
    })
};

var res = {
  meth: res_meth,
  var: res_var
};

var bye_meth = {
  call_obj: (function (obj) {
      return obj.bye;
    }),
  make_obj: (function (v) {
      return {
              bye: v
            };
    })
};

var bye_var = {
  match_var: (function ($$var) {
      if (typeof $$var === "object" && $$var.NAME === "bye") {
        return Caml_option.some($$var.VAL);
      }
      
    }),
  make_var: (function (v) {
      return {
              NAME: "bye",
              VAL: v
            };
    })
};

var bye = {
  meth: bye_meth,
  var: bye_var
};

var finish = [
  undefined,
  undefined,
  undefined
];

exports.lens_a = lens_a;
exports.lens_b = lens_b;
exports.lens_c = lens_c;
exports.a = a;
exports.b = b;
exports.c = c;
exports.add = add;
exports.res = res;
exports.bye = bye;
exports.finish = finish;
/* No side effect */
