// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var MainSide = {};

function setOnMessage(f) {
  return (f => { onmessage = f })(f);
}

var WorkerSide = {
  setOnMessage: setOnMessage
};

exports.MainSide = MainSide;
exports.WorkerSide = WorkerSide;
/* No side effect */
