// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var MainSide = {};

function postMessage(v) {
  return (v => self.postMessage(v))(v);
}

function setOnMessage(f) {
  return (f => { onmessage = f })(f);
}

var WorkerSide = {
  postMessage: postMessage,
  setOnMessage: setOnMessage
};

exports.MainSide = MainSide;
exports.WorkerSide = WorkerSide;
/* No side effect */
